### ISSUE TITLE
外服换肤13.7

### ISSUE THREAD

**Issue by tianya0529** [R3nzTheCodeGOD/R3nzSkin#393] opened 2023-04-10 14:46 UTC
![图片](https://user-images.githubusercontent.com/63766756/230924643-ffa41bc0-13dd-4985-b6ec-cf27c5938ae2.png)
[下载地址](https://wwi.lanzoup.com/b01em26zg ) 密码:edbp

**Comment by Deaiman** [comment] 2023-04-10 15:03
I think its a trojan. Where is your virustotal link man ?

**Comment by Deaiman** [comment] 2023-04-10 15:06
I will open this in virtual machine and i will tell you guys its real or scam

**Comment by Deaiman** [comment] 2023-04-10 15:08
Or maybe just put a virustotal link for us man ?

**Comment by tianya0529** [comment] 2023-04-10 15:18
> Or maybe just put a virustotal link for us man ?



I don't want to provide it for you to use, I only provide it for my Chinese compatriots to use
Because you don't understand this cloud disk, consider it a viral webpage

**Comment by 0bsr** [comment] 2023-04-10 15:42
在每个服务器上都能工作? @tianya0529

**Comment by IAKILL** [comment] 2023-04-10 16:15
Does this work for x64 client version?

**Comment by austenseo** [comment] 2023-04-10 16:54
> ![图片](https://user-images.githubusercontent.com/63766756/230924643-ffa41bc0-13dd-4985-b6ec-cf27c5938ae2.png) [下载地址](https://wwi.lanzoup.com/b01em26zg) 密码:edbp

how to run it can you give us the steps
TY for yoyr effort

**Comment by Fiethsings** [comment] 2023-04-10 17:03
> Does this work for x64 client version?

Yes, I've tested here on BR server.  
A things to note: You need to enable DX11 for it work. You can do it by disabling the DX9 legacy mode on the client settings or by changing the game.cfg (C:\Riot Games\League of Legends\Config). There's an image on the folder showing how to do it.

Here's the [VirusTotal scan](https://www.virustotal.com/gui/file/037ad56b1ab86491d73ae8aa23a7f34475d2660ff9ff216694205035b95eb813/detection).

> how to run it can you give us the steps

Here you go.

![pic_1](https://user-images.githubusercontent.com/130254968/230952224-0319f8df-d1fc-4ef8-a580-44163395bab7.png)

![pic_3](https://user-images.githubusercontent.com/130254968/230952247-72c8c5b9-1c01-404c-b45a-2ca23a23c994.png)

![pic_2](https://user-images.githubusercontent.com/130254968/230952285-8fdbc274-fdc4-44cc-beff-16545a1ba042.png)

**Comment by IAKILL** [comment] 2023-04-10 17:06
@Fiethsings Uh the virustotal looks scary tho no?

**Comment by austenseo** [comment] 2023-04-10 17:13
> > Does this work for x64 client version?
> 
> Yes, I've tested here on BR server. A things to note: You need to enable DX11 for it work. You can do it by disabling the DX9 legacy mode on the client settings or by changing the game.cfg (C:\Riot Games\League of Legends\Config). There's an image on the folder showing how to do it.
> 
> Here's the [VirusTotal scan](https://www.virustotal.com/gui/file/037ad56b1ab86491d73ae8aa23a7f34475d2660ff9ff216694205035b95eb813/detection).
> 
> > how to run it can you give us the steps
> 
> Here you go.
> 
> ![pic_1](https://user-images.githubusercontent.com/130254968/230952224-0319f8df-d1fc-4ef8-a580-44163395bab7.png)
> 
> ![pic_3](https://user-images.githubusercontent.com/130254968/230952247-72c8c5b9-1c01-404c-b45a-2ca23a23c994.png)
> 
> ![pic_2](https://user-images.githubusercontent.com/130254968/230952285-8fdbc274-fdc4-44cc-beff-16545a1ba042.png)

can i rech you on insta or discord i think i'm having a problem and i didn't know what to do

**Comment by AndroidDeep** [comment] 2023-04-10 17:27
亲测可用，感谢老哥分享。又可以愉快的去外服坑人了

**Comment by alphaaced** [comment] 2023-04-10 17:33
> ![图片](https://user-images.githubusercontent.com/63766756/230924643-ffa41bc0-13dd-4985-b6ec-cf27c5938ae2.png)
> [下载地址](https://wwi.lanzoup.com/b01em26zg ) 密码:edbp

Its only for chinese servers?

**Comment by minazuki522** [comment] 2023-04-10 17:34
> > Does this work for x64 client version?
> 
> Yes, I've tested here on BR server. A things to note: You need to enable DX11 for it work. You can do it by disabling the DX9 legacy mode on the client settings or by changing the game.cfg (C:\Riot Games\League of Legends\Config). There's an image on the folder showing how to do it.
> 
> Here's the [VirusTotal scan](https://www.virustotal.com/gui/file/037ad56b1ab86491d73ae8aa23a7f34475d2660ff9ff216694205035b95eb813/detection).
> 
> > how to run it can you give us the steps
> 
> Here you go.
> 
> ![pic_1](https://user-images.githubusercontent.com/130254968/230952224-0319f8df-d1fc-4ef8-a580-44163395bab7.png)
> 
> ![pic_3](https://user-images.githubusercontent.com/130254968/230952247-72c8c5b9-1c01-404c-b45a-2ca23a23c994.png)
> 
> ![pic_2](https://user-images.githubusercontent.com/130254968/230952285-8fdbc274-fdc4-44cc-beff-16545a1ba042.png)

oh, you're a brazilian fellow? (se sim, fala pa nois como funfa esse programa)

**Comment by alphaaced** [comment] 2023-04-10 17:35
> > Does this work for x64 client version?
> 
> Yes, I've tested here on BR server.  
> A things to note: You need to enable DX11 for it work. You can do it by disabling the DX9 legacy mode on the client settings or by changing the game.cfg (C:\Riot Games\League of Legends\Config). There's an image on the folder showing how to do it.
> 
> Here's the [VirusTotal scan](https://www.virustotal.com/gui/file/037ad56b1ab86491d73ae8aa23a7f34475d2660ff9ff216694205035b95eb813/detection).
> 
> > how to run it can you give us the steps
> 
> Here you go.
> 
> ![pic_1](https://user-images.githubusercontent.com/130254968/230952224-0319f8df-d1fc-4ef8-a580-44163395bab7.png)
> 
> ![pic_3](https://user-images.githubusercontent.com/130254968/230952247-72c8c5b9-1c01-404c-b45a-2ca23a23c994.png)
> 
> ![pic_2](https://user-images.githubusercontent.com/130254968/230952285-8fdbc274-fdc4-44cc-beff-16545a1ba042.png)
> 

Do u have discord so i can message you?.

**Comment by minazuki522** [comment] 2023-04-10 17:40
well, I don't know if it is a virus or not, but thank you for showing that it is possible to make it work again

**Comment by alphaaced** [comment] 2023-04-10 17:43
> If someone wonders it works on x64, it acts quite weird but works. Also use at your own risk

Can u help me please? do u have discord

**Comment by IAKILL** [comment] 2023-04-10 17:44
@alphaaced Send yours i will add you

**Comment by alphaaced** [comment] 2023-04-10 17:46
> @alphaaced Send yours i will add you

! alpha ッ#3398

**Comment by Xrndf** [comment] 2023-04-10 17:56
> ![图片](https://user-images.githubusercontent.com/63766756/230924643-ffa41bc0-13dd-4985-b6ec-cf27c5938ae2.png) [下载地址](https://wwi.lanzoup.com/b01em26zg) 密码:edbp

do you have source code? i will recode it to make it in english language

**Comment by miyuishere** [comment] 2023-04-10 17:56
Thank you for sharing!

**Comment by IAKILL** [comment] 2023-04-10 17:59
@tianya0529 Thanks a lot for sharing ! Really apriciate your work, could you please make english version or make github repo with source code? So someone can make english langauge

**Comment by iwilltry7** [comment] 2023-04-10 18:01
It's doesnt work for me on euw eng client nothing happens.

**Comment by IAKILL** [comment] 2023-04-10 18:01
> It's doesnt work for me on euw eng client nothing happens.

Have you disabled DX9 in settings in client?

**Comment by miyuishere** [comment] 2023-04-10 18:05
Everything works nice thank you! Is there possibility to make english version? Because it is in chinese, I have no idea which skin I am picking lol

**Comment by iwilltry7** [comment] 2023-04-10 18:05
> > It's doesnt work for me on euw eng client nothing happens.
> 
> Have you disabled DX9 in settings in client?

Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.

**Comment by IAKILL** [comment] 2023-04-10 18:06
> > > It's doesnt work for me on euw eng client nothing happens.
> > 
> > 
> > Have you disabled DX9 in settings in client?
> 
> Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
Okay, but i think its not needed to reinstall league xd

**Comment by iwilltry7** [comment] 2023-04-10 18:22
> > > > It's doesnt work for me on euw eng client nothing happens.
> > > 
> > > 
> > > Have you disabled DX9 in settings in client?
> > 
> > 
> > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > Okay, but i think its not needed to reinstall league xd
 Yeah its doesnt work and i have thi s
![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)

**Comment by Xrndf** [comment] 2023-04-10 18:27
> 

no it isn't, working fine, if u wanna check if it is a virus, go to virtual machine, or use any.run

**Comment by miyuishere** [comment] 2023-04-10 18:31
> > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > 
> > > > 
> > > > Have you disabled DX9 in settings in client?
> > > 
> > > 
> > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > Okay, but i think its not needed to reinstall league xd
> > > Yeah its doesnt work and i have thi s
> > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)

Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^

**Comment by alphaaced** [comment] 2023-04-10 18:33
> > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > 
> > > > > 
> > > > > Have you disabled DX9 in settings in client?
> > > > 
> > > > 
> > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > Okay, but i think its not needed to reinstall league xd
> > > > Yeah its doesnt work and i have thi s
> > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> 
> bro they are scamming its just a virus 

i tested it, its safe and not a virus it works. But the problem is with stopping the tool. If you close the exe and still load in again, this skins are there. How do we stop it?

**Comment by miyuishere** [comment] 2023-04-10 18:33
> > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > 
> > > > > 
> > > > > Have you disabled DX9 in settings in client?
> > > > 
> > > > 
> > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > Okay, but i think its not needed to reinstall league xd
> > > > Yeah its doesnt work and i have thi s
> > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> 
> bro they are scamming its just a virus

Don't spread misinfo if you don't know anything

**Comment by alphaaced** [comment] 2023-04-10 18:36
> > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > 
> > > > > 
> > > > > Have you disabled DX9 in settings in client?
> > > > 
> > > > 
> > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > Okay, but i think its not needed to reinstall league xd
> > > > Yeah its doesnt work and i have thi s
> > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> 
> Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^
> 

which button turns off the changer?

**Comment by miyuishere** [comment] 2023-04-10 18:36
> > > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > > 
> > > > > > 
> > > > > > Have you disabled DX9 in settings in client?
> > > > > 
> > > > > 
> > > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > > Okay, but i think its not needed to reinstall league xd
> > > > > Yeah its doesnt work and i have thi s
> > > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> > 
> > 
> > Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^
> 
> which button turns off the changer?

Second

**Comment by alphaaced** [comment] 2023-04-10 18:38
> > > > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > > > 
> > > > > > > 
> > > > > > > Have you disabled DX9 in settings in client?
> > > > > > 
> > > > > > 
> > > > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > > > Okay, but i think its not needed to reinstall league xd
> > > > > > Yeah its doesnt work and i have thi s
> > > > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> > > 
> > > 
> > > Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^
> > 
> > which button turns off the changer?
> 
> Second

Can u snip it? is it the small ones or the ones below the blue ( the 2 big ones)

**Comment by austenseo** [comment] 2023-04-10 18:39
> Everything works nice thank you! Is there possibility to make english version? Because it is in chinese, I have no idea which skin I am picking lol

Hi can you tell me what you do to turn it on and thank you idk i keep havinge blue screen

**Comment by iwilltry7** [comment] 2023-04-10 18:39
Well it's still doesnt work idkn nothing happens DX9 is off and DX11 is on in the config.cfg

**Comment by miyuishere** [comment] 2023-04-10 18:39
> > > > > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Have you disabled DX9 in settings in client?
> > > > > > > 
> > > > > > > 
> > > > > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > > > > Okay, but i think its not needed to reinstall league xd
> > > > > > > Yeah its doesnt work and i have thi s
> > > > > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> > > > 
> > > > 
> > > > Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^
> > > 
> > > 
> > > which button turns off the changer?
> > 
> > 
> > Second
> 
> Can u snip it? is it the small ones or the ones below the blue ( the 2 big ones)

Big ones ^^ Idk for what those small ones are so I didn't touch them

**Comment by iwilltry7** [comment] 2023-04-10 18:44
Well nevermind it's working now idkn why, thanks i guess but an eng ver would be cool if possible but im ok with it now.

**Comment by alphaaced** [comment] 2023-04-10 18:45
> > > > > > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Have you disabled DX9 in settings in client?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > > > > > Okay, but i think its not needed to reinstall league xd
> > > > > > > > Yeah its doesnt work and i have thi s
> > > > > > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> > > > > 
> > > > > 
> > > > > Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^
> > > > 
> > > > 
> > > > which button turns off the changer?
> > > 
> > > 
> > > Second
> > 
> > Can u snip it? is it the small ones or the ones below the blue ( the 2 big ones)
> 
> Big ones ^^ Idk for what those small ones are so I didn't touch them

Do u have discord? im pressing it and nothing happens

**Comment by iwilltry7** [comment] 2023-04-10 18:48
> 

I used the right small cercle and i clicked on the left big text.

**Comment by iwilltry7** [comment] 2023-04-10 18:48
> > > > > > > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Have you disabled DX9 in settings in client?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > > > > > > Okay, but i think its not needed to reinstall league xd
> > > > > > > > > Yeah its doesnt work and i have thi s
> > > > > > > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> > > > > > 
> > > > > > 
> > > > > > Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^
> > > > > 
> > > > > 
> > > > > which button turns off the changer?
> > > > 
> > > > 
> > > > Second
> > > 
> > > 
> > > Can u snip it? is it the small ones or the ones below the blue ( the 2 big ones)
> > 
> > 
> > Big ones ^^ Idk for what those small ones are so I didn't touch them
> 
> Do u have discord? im pressing it and nothing happens

I used the right small cercle and i clicked on the left big text.

**Comment by alphaaced** [comment] 2023-04-10 18:50
> > > > > > > > > > > > It's doesnt work for me on euw eng client nothing happens.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Have you disabled DX9 in settings in client?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Yes but I quickly reinstalled the game to start again the manipulation of the beginning I keep you informed.
> > > > > > > > > > Okay, but i think its not needed to reinstall league xd
> > > > > > > > > > Yeah its doesnt work and i have thi s
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/130395938/230966773-e4a0d521-4181-400a-8f3d-5f950141b254.png)
> > > > > > > 
> > > > > > > 
> > > > > > > Click the first button, it turns on the skin changer, the other one turns it off. Just join a training game and try it out, you can close it by clicking ins key, hope I helped ^^
> > > > > > 
> > > > > > 
> > > > > > which button turns off the changer?
> > > > > 
> > > > > 
> > > > > Second
> > > > 
> > > > 
> > > > Can u snip it? is it the small ones or the ones below the blue ( the 2 big ones)
> > > 
> > > 
> > > Big ones ^^ Idk for what those small ones are so I didn't touch them
> > 
> > Do u have discord? im pressing it and nothing happens
> 
> I used the right small cercle and i clicked on the left big text.

ok i fixed it, you can stop it midgame. Only after game is finished

**Comment by Shionned** [comment] 2023-04-10 19:39
Its worked, but my game starts freezing so much (i had 300+ fps in practice tool but game works weird), someone had this problem?
And second button didn't off my skinchanger

**Comment by Fiethsings** [comment] 2023-04-10 19:51
> Its worked, but my game starts freezing so much (i had 300+ fps in practice tool but game works weird), someone had this problem? And second button didn't off my skinchanger

Is your game stuttering when you move the mouse but if you leave it alone it runs just fine?
If that's the case then check your mouse polling rate and try reducing it. If it's 1000Hz then drop it to 500Hz or 250Hz and check if it's still stuttering.

**Comment by austenseo** [comment] 2023-04-10 19:53
Hey pleas help me i trryed everything and still don't work

**Comment by Xertoo** [comment] 2023-04-10 20:39
I mean it's working but when i played game it had serious fps drops, idk if this was beacuse of yuumi, but after every game restart fps drops were gone. After every death they returned. (sorry for bad english)

**Comment by Shionned** [comment] 2023-04-10 20:54
> 
> > Its worked, but my game starts freezing so much (i had 300+ fps in practice tool but game works weird), someone had this problem? And second button didn't off my skinchanger
> 
> Is your game stuttering when you move the mouse but if you leave it alone it runs just fine? If that's the case then check your mouse polling rate and try reducing it. If it's 1000Hz then drop it to 500Hz or 250Hz and check if it's still stuttering.
it helped, thanks

**Comment by Xrndf** [comment] 2023-04-10 21:25
I found diffrent version of skinchanger, it's on Chinese site but in game there's english gui, it is based on r3nzskin
https://www.118pan.com/o17188
it dont have virus as i checked
password for rar is 1314

**Comment by alphaaced** [comment] 2023-04-10 22:07
> I found diffrent version of skinchanger, it's on Chinese site but in game there's english gui, it is based on r3nzskin
> https://www.118pan.com/o17188
> it dont have virus as i checked
> password for rar is 1314

Can you assist me? im loading the exe and nothing happens, its also all Chinese. You have discord?

**Comment by alphaaced** [comment] 2023-04-10 23:30
> I found diffrent version of skinchanger, it's on Chinese site but in game there's english gui, it is based on r3nzskin https://www.118pan.com/o17188 it dont have virus as i checked password for rar is 1314

i dont think this has english/ works. beware guys

**Comment by austenseo** [comment] 2023-04-11 00:00
> > I found diffrent version of skinchanger, it's on Chinese site but in game there's english gui, it is based on r3nzskin
> > https://www.118pan.com/o17188
> > it dont have virus as i checked
> > password for rar is 1314
> 
> Can you assist me? im loading the exe and nothing happens, its also all Chinese. You have discord?

I have the same problem here

**Comment by yukasakisg** [comment] 2023-04-11 02:24
> ![图片](https://user-images.githubusercontent.com/63766756/230924643-ffa41bc0-13dd-4985-b6ec-cf27c5938ae2.png) [下载地址](https://wwi.lanzoup.com/b01em26zg) 密码：edbp

感谢作者大大更新，不过现在有点小问题，开启换肤之后fps动不动就掉，很难受，希望作者大大能够优化一下·

**Comment by Piglet1994** [comment] 2023-04-11 03:46
I should tell you guys, this is not free software (you should pay to subscribe). What's more, you don't know if it's safe.

**Comment by Piglet1994** [comment] 2023-04-11 03:48
This ticket is more like an AD.

**Comment by E1ev2n** [comment] 2023-04-11 04:50
黑肉来了！

**Comment by yukasakisg** [comment] 2023-04-11 04:56
> 我应该告诉你们，这不是自由软件（你需要订阅）。更重要的是，你不知道它是否安全。

You may not use it, but please do not defame the author. Someone has updated the program that can be used and it is not for you to say hi. If you think it is a virus, please provide evidence, otherwise please do not defame the author

**Comment by jinishizaisitaimei** [comment] 2023-04-11 05:20
爱死了老哥

**Comment by IAKILL** [comment] 2023-04-11 07:38
> 感谢作者大大更新，不过现在有点小问题，开启换肤之后fps动不动就掉，很难受，希望作者大大能够优化一下·

Try decreasing mouse refresh rate, it should be in your mouse software program
Few ppl had this issue they decreased the refresh rate from 1k tp like 500HZ
Also check if you have DX11 (uncheck DX9 in client settings)


嘗試降低鼠標刷新率，它應該在您的鼠標軟件程序中
很少有人遇到這個問題，他們將刷新率從 1k tp 降低到 500HZ
還要檢查您是否有 DX11（在客戶端設置中取消選中 DX9）

**Comment by myc00** [comment] 2023-04-11 08:16
非常感谢！！很好用

**Comment by Xrndf** [comment] 2023-04-11 08:59
> > > I found diffrent version of skinchanger, it's on Chinese site but in game there's english gui, it is based on r3nzskin
> > > https://www.118pan.com/o17188
> > > it dont have virus as i checked
> > > password for rar is 1314
> > 
> > 
> > Can you assist me? im loading the exe and nothing happens, its also all Chinese. You have discord?
> 
> I have the same problem here

what you mean by nothing happens
![image](https://user-images.githubusercontent.com/130395212/231109719-3f1928bb-9b1a-4fdc-86e6-319e5dcf1e29.png)
after opening exe there should be this menu
dont click anything just go to game
to close/open menu use HOME button

**Comment by alphaaced** [comment] 2023-04-11 09:06
> > > > I found diffrent version of skinchanger, it's on Chinese site but in game there's english gui, it is based on r3nzskin
> > > > https://www.118pan.com/o17188
> > > > it dont have virus as i checked
> > > > password for rar is 1314
> > > 
> > > 
> > > Can you assist me? im loading the exe and nothing happens, its also all Chinese. You have discord?
> > 
> > I have the same problem here
> 
> what you mean by nothing happens
> ![image](https://user-images.githubusercontent.com/130395212/231109719-3f1928bb-9b1a-4fdc-86e6-319e5dcf1e29.png)
> after opening exe there should be this menu
> dont click anything just go to game
> to close/open menu use HOME button

Do you have anyway i can contact you? discord? Instagram? telegram?

**Comment by Xrndf** [comment] 2023-04-11 09:14
> > > > > I found diffrent version of skinchanger, it's on Chinese site but in game there's english gui, it is based on r3nzskin
> > > > > https://www.118pan.com/o17188
> > > > > it dont have virus as i checked
> > > > > password for rar is 1314
> > > > 
> > > > 
> > > > Can you assist me? im loading the exe and nothing happens, its also all Chinese. You have discord?
> > > 
> > > 
> > > I have the same problem here
> > 
> > 
> > what you mean by nothing happens
> > ![image](https://user-images.githubusercontent.com/130395212/231109719-3f1928bb-9b1a-4fdc-86e6-319e5dcf1e29.png)
> > after opening exe there should be this menu
> > dont click anything just go to game
> > to close/open menu use HOME button
> 
> Do you have anyway i can contact you? discord? Instagram? telegram?

Xrnd#1610

**Comment by Thelonger666** [comment] 2023-04-11 11:33
thank you,you are my hero

**Comment by IAKILL** [comment] 2023-04-11 11:58
@alphaaced is it really safe? Could you please send ingame photo? It shows 10 more virusses on totalvirus than the r4

**Comment by TheNei** [comment] 2023-04-11 12:09
老哥你整个中文版让很多老外都看不懂啦😂

**Comment by alphaaced** [comment] 2023-04-11 12:10
> @alphaaced is it really safe? Could you please send ingame photo? It shows 10 more virusses on totalvirus than the r4

maybe not, i dont know. Try it yourself

**Comment by Deaiman** [comment] 2023-04-11 12:12
> > @alphaaced is it really safe? Could you please send ingame photo? It shows 10 more virusses on totalvirus than the r4
> 
> maybe not, i dont know. Try it yourself

the guy showed me its working i saw it with my eyes %100 but i think the program working with trojan . I mean yes program is still work but with trojans

**Comment by alphaaced** [comment] 2023-04-11 12:12
> > > @alphaaced is it really safe? Could you please send ingame photo? It shows 10 more virusses on totalvirus than the r4
> > 
> > maybe not, i dont know. Try it yourself
> 
> the guy showed me its working i saw it with my eyes %100 but i think the program working with trojan . I mean yes program is still work but with trojans

The english version or the r4 one?

**Comment by slowloriss** [comment] 2023-04-11 16:11
> ![图片](https://user-images.githubusercontent.com/63766756/230924643-ffa41bc0-13dd-4985-b6ec-cf27c5938ae2.png) [下载地址](https://wwi.lanzoup.com/b01em26zg) 密码:edbp

即使我已經使用了dx11遊玩 遊戲幀率明顯下降了許多
下面分別是正常遊玩和with R4遊玩 可以看到平均幀率明顯下降了許多 遊戲裡可以感受到明顯的差異
000020.619| ALWAYS| =================== Perf Stats (all in ms) =========================
000020.619| ALWAYS| Average Frame Time:    5.19
000020.619| ALWAYS| Average FPS:           192.59 fps
000020.619| ALWAYS| StdDev Frame Time:     4.03
000020.619| ALWAYS| Max Frame Time:        132.31
000020.619| ALWAYS| Ave GPU Frame Time:    1.18
000020.619| ALWAYS| StdDev GPU Frame Time: 0.69
000020.619| ALWAYS| Max GPU Frame Time:    22.00


000059.943| ALWAYS| Average Frame Time:    6.68
000059.943| ALWAYS| Average FPS:           149.80 fps
000059.943| ALWAYS| StdDev Frame Time:     12.91
000059.943| ALWAYS| Max Frame Time:        332.06
000059.943| ALWAYS| Ave GPU Frame Time:    1.22
000059.943| ALWAYS| StdDev GPU Frame Time: 0.60
000059.943| ALWAYS| Max GPU Frame Time:    8.32


然後是皮膚名稱列表 在遊戲中全部都是顯示??????? 我猜測是框架元件編碼的特性
即使我在C:\R3nskin 這個名稱列表文件嘗試修改它 但似乎不起作用

**Comment by switchblade0003** [comment] 2023-04-11 19:24
ye , need some help mister china tianya0529 is there a way to uninstall software without changing path to the game or reinstalling game itself?

**Comment by minazuki522** [comment] 2023-04-11 19:49
how can I turn it off?

**Comment by slowloriss** [comment] 2023-04-11 20:20
> 
I think you only need remove C:\Windows\111.dll and C:\Windows\wegame.dll
and C:\R3nzSkin
if you don't need logitechled.dll(fake one) remove also.

**Comment by tianya0529** [comment] 2023-04-12 00:37
> 



Click the button on the right to close

**Comment by tianya0529** [comment] 2023-04-12 00:37
> ye , need some help mister china tianya0529 is there a way to uninstall software without changing path to the game or reinstalling game itself?



Click the button on the right to close

**Comment by minazuki522** [comment] 2023-04-12 11:30
> > 
> 
> I think you only need remove C:\Windows\111.dll and C:\Windows\wegame.dll and C:\R3nzSkin if you don't need logitechled.dll(fake one) remove also.

how can I find those?

**Comment by minazuki522** [comment] 2023-04-12 11:38
> > ye , need some help mister china tianya0529 is there a way to uninstall software without changing path to the game or reinstalling game itself?
> 
> Click the button on the right to close

I do it but it does not work anyway, the program keeps on no matter what

**Comment by tianya0529** [comment] 2023-04-12 11:40
> > > ye , need some help mister china tianya0529 is there a way to uninstall software without changing path to the game or reinstalling game itself?
> > 
> > 
> > Click the button on the right to close
> 
> I do it but it does not work anyway, the program keeps on no matter what

delete \Riot Games\League of Legends\Game\LogitechLed.dll and C:\Windows\111.dll and C:\Windows\wegame.dll

**Comment by minazuki522** [comment] 2023-04-12 14:36
> > > > ye , need some help mister china tianya0529 is there a way to uninstall software without changing path to the game or reinstalling game itself?
> > > 
> > > 
> > > Click the button on the right to close
> > 
> > 
> > I do it but it does not work anyway, the program keeps on no matter what
> 
> delete \Riot Games\League of Legends\Game\LogitechLed.dll and C:\Windows\111.dll and C:\Windows\wegame.dll

thank you very much!

**Comment by Jejfn** [comment] 2023-04-14 17:49
It works, thank you my chinese brother!

**Comment by hotline1337** [comment] 2023-04-16 20:43
Issue not associated with the current project. Binaries are not allowed to be shared here.

**Closed by hotline1337** 2023-04-16 20:43 UTC
