### ISSUE TITLE
Failed to find pattern error when I inject

### ISSUE THREAD

**Issue by Felldarknesspaw** [R3nzTheCodeGOD/R3nzSkin#128] opened 2022-06-09 14:58 UTC
![image](https://user-images.githubusercontent.com/107200600/172878450-31f6b708-25ae-4913-b053-8099b59cdddf.png)

**Comment by R3nzTheCodeGOD** [comment] 2022-06-09 16:04
Are you kidding me, did you look at the commit I sent yesterday? I think I'll close the issues section of this repo.

**Comment by Felldarknesspaw** [comment] 2022-06-09 18:41
> Are you kidding me, did you look at the commit I sent yesterday? I think I'll close the issues section of this repo.

yes I saw it , but I have no idea what to do and how to do it

**Comment by hotline1337** [comment] 2022-06-10 09:21
there is a new pattern not working tho

**Comment by Aixeaudia** [comment] 2022-06-10 13:16
> ![image](https://user-images.githubusercontent.com/58574988/172924796-221bfc53-8d80-4bf5-9f42-a69a9dafc94e.png)

it still don't work

**Comment by Aixeaudia** [comment] 2022-06-10 13:16
it still doesn't work

**Comment by R3nzTheCodeGOD** [comment] 2022-06-10 13:32
# TR
![image](https://user-images.githubusercontent.com/58574988/173076087-2a891596-7557-4991-a0fd-9226b90c723b.png)
# EUW
![image](https://user-images.githubusercontent.com/58574988/173076314-b00ff7cb-880b-4464-85b8-77c659a638c9.png)

**Comment by Aixeaudia** [comment] 2022-06-10 14:17
![image](https://user-images.githubusercontent.com/81640571/173085405-b2d67d4e-7236-47ea-95e9-eb1662b2af23.png)
it show me this with the new commit

**Comment by R3nzTheCodeGOD** [comment] 2022-06-10 14:28
> ![image](https://user-images.githubusercontent.com/81640571/173085405-b2d67d4e-7236-47ea-95e9-eb1662b2af23.png) it show me this with the new commit

Server ?

**Comment by Aixeaudia** [comment] 2022-06-10 14:35
> > ![image](https://user-images.githubusercontent.com/81640571/173085405-b2d67d4e-7236-47ea-95e9-eb1662b2af23.png) it show me this with the new commit
> 
> Server ?

EUW

**Comment by R3nzTheCodeGOD** [comment] 2022-06-10 14:48
> > > ![image](https://user-images.githubusercontent.com/81640571/173085405-b2d67d4e-7236-47ea-95e9-eb1662b2af23.png) it show me this with the new commit
> > 
> > 
> > Server ?
> 
> EUW
The problem is in your game try to reinstall your game because it works fine on euw server.

**Comment by hotline1337** [comment] 2022-06-12 09:47
> > > > ![image](https://user-images.githubusercontent.com/81640571/173085405-b2d67d4e-7236-47ea-95e9-eb1662b2af23.png) it show me this with the new commit
> > > 
> > > 
> > > Server ?
> > 
> > 
> > EUW
> > The problem is in your game try to reinstall your game because it works fine on euw server.

same problem on EUNE

**Comment by neptules** [comment] 2022-06-16 18:23
I get the same error BUT the skin changer works perfectly fine. I just close it and get back to the game [Server: TR]

**Comment by R3nzTheCodeGOD** [comment] 2022-06-25 21:00
Your computers seem to unpack the encrypted lol exe slowly. If you inject R3nzSkin after waiting for a while, you will not get such an error.

**Closed by R3nzTheCodeGOD** 2022-06-25 21:00 UTC
Labels: Ultra Mega Bruh Issue
